[package]
name = "ui-test-egui"
edition.workspace = true
license.workspace = true
publish = false
version.workspace = true

[[bin]]
name = "deckhand-ui-egui"
path = "src/main.rs"

[dependencies]
ui-test-common = { path = "../ui-test-common" }
ipc = { path = "../ipc" }
config = { path = "../config" }
eframe.workspace = true
rfd.workspace = true
