[package]
name = "ui-test-gtk"
edition.workspace = true
license.workspace = true
publish = false
version.workspace = true

[[bin]]
name = "deckhand-ui-gtk"
path = "src/main.rs"

[dependencies]
ui-test-common = { path = "../ui-test-common" }
ipc = { path = "../ipc" }
config = { path = "../config" }
gtk4.workspace = true
async-channel.workspace = true
rfd.workspace = true
